### ISSUE TITLE
Error when using det-metrics with video dataset

### ISSUE THREAD

**Issue by Zwicii** [SEA-AI/seametrics#10]
**Describe the bug**
When attempting to utilize the det-metrics with a video dataset, I encountered the following error: _ValueError: DatasetView has no field 'frames[].cerulean-level-17_11_2023_RL_SPLIT_ep147_CNN'_

**To Reproduce**
Instantiate the PayloadProcessor with the following parameters:
dataset_name: "SENTRY_VIDEOS_DATASET_QA"
gt_field: "ground_truth_det"
models: ["cerulean-level-17_11_2023_RL_SPLIT_ep147_CNN"]
sequence_list: ["Sentry_2023_02_08_PROACT_CELADON_@6m_MOB_2023_02_08_12_47_47"]
data_type: "thermal"

**Expected behavior**
Metrics should be calculated

**Screenshots**
![image](https://github.com/SEA-AI/seametrics/assets/29953180/76fedd59-6b28-4206-a20e-37fbd8986625)

**Comment by kevinconka** [comment]
@Zwicii can you checkout this and test?
[bugfix/video-fieldname-error](https://github.com/SEA-AI/seametrics/tree/bugfix/video-fieldname-error)
